
---
- hosts: all
  gather_facts: false
  tasks:
  # IMPORTANTE: verificar as variáveis no template antes de executar este playbook!!
  # (exemplo)
  # NETofINTERF:"192.168.0.0/16"
  # PORTofSERVICE:"80"
  # PROTO:"tcp"
  # ACT:"reject"
  # CHAIN:"input"
  # COMMENTofRULE:"bloqueio porta 80"

  - name: Get IP address to create de rule
    routeros_command:
      commands:
        - "{ :local NETofINTERF {{ NETofINTERF }}; :local GETIPADDRESS [/ip address get [ find where address in $NETofINTERF ]]; :global IPADDRESS [:pick $GETIPADDRESS 2]; }"       

  - name: Adding a new firewall filter rule
    routeros_command:
      commands:
        - "{ :local PORTofSERVICE {{ PORTofSERVICE }}; :local PROTO {{ PROTO }}; :local ACT {{ ACT }}; :local CHAIN {{ CHAIN }}; :local COMMENTofRULE {{ COMMENTofRULE }}; :put [/ip firewall filter add dst-address=$IPADDRESS port=$PORTofSERVICE protocol=$PROTO action=$ACT chain=$CHAIN comment=$COMMENTofRULE ] }"
