
---
- hosts: all
  gather_facts: false
  tasks:
  # importante chegar as variáveis no template antes de executar esse playbook

  - name: Get IP address to create a firewall rule
    routeros_command:
      commands:
        - "{:local NETOWRKofINTERFACE {{ NETofINTERF }}; :local GETIPADDRESS [/ip address get [ find where address in $NETOWRKofINTERFACE ]]; :global IPADDRESS [:pick $GETIPADDRESS 2];}"

  - name: Adding a new firewall filter rule
    routeros_command:
      commands:
        - ":put [/ip firewall filter add dst-address=$IPADDRESS port={{ PORTofSERVICE }} protocol={{ PROTO }} action={{ ACT }} chain={{ CHAIN }} comment={{ COMMENTofRULE }}]"
